job_roles:
  - "Application Support"
  - "Production Support"
  - "Cloud Support"
#  - "Cloud Engineer"
#  - "Junior Devops Engineer"
 # - "L1 Support"
  

locations:
  - "Pune"
 # - "Mumbai"
  - "Hyderabad"
  - "Bangalore"
#  - "Remote"

experience:
  min: 0
  max: 5

platforms:
  indeed: false # false for now, Phase 2
  naukri: true
  linkedin: false  # false for now, Phase 3

apply_limit_per_day: 40
min_ai_score: 6

filters:
   posted_within_days: 1
   exclude_keywords:
    - "senior manager"
    - "director"
    - "principal engineer"
    - "staff engineer"
    - "vp of"
    - "head of"
    - "10+ years"
    - "15 years"
    - "lead engineer"
    - "tech lead"
    - "architect"